export { default as Main} from './Main'
export { default as Auth} from './Auth'
export { default as Content} from './Content'
export { default as Stocks} from './Stocks'
export { default as StockProfile} from './StockProfile'
